name: Auto Assign Reviewers
on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
             YamasakiTatsuki
             dc-shinochi-haru
             DC-FujiiHaruto
          numberOfReviewers: 2
