name: Auto Assign Reviewers
on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
             YamasakiTatsuki
             dc-shinochi-haru
             DC-FujiiHaruto
          number-of-reviewers: 2
